-- MySQL Script generated by MySQL Workbench
-- Sat Feb  5 15:59:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dblaguarida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dblaguarida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dblaguarida` DEFAULT CHARACTER SET utf8 ;
USE `dblaguarida` ;

-- -----------------------------------------------------
-- Table `dblaguarida`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dblaguarida`.`Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `dblaguarida`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dblaguarida`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `dblaguarida`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dblaguarida`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `price` DECIMAL NOT NULL,
  `image` BLOB NOT NULL,
  `descrip` VARCHAR(200) NOT NULL,
  `Status_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Status_id`, `Category_id`),
  CONSTRAINT `fk_Products_Status`
    FOREIGN KEY (`Status_id`)
    REFERENCES `dblaguarida`.`Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `dblaguarida`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `dblaguarida`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dblaguarida`.`Permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `dblaguarida`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dblaguarida`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_alias` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `avatar` BLOB NULL,
  `Permission_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Permission_id`),
  CONSTRAINT `fk_User_Permission1`
    FOREIGN KEY (`Permission_id`)
    REFERENCES `dblaguarida`.`Permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
